use security:recommended

@use feature : HPC_ANNEX

# For user convenience, allow the user to schedule an annex before creating an annex job
HPC_ANNEX_REQUIRE_JOB = false

# Also for user convenience, auto-route jobs to the annex since all EPs are contributed
# via annex
JOB_TRANSFORM_NAMES = AllJobsToAnnex $(JOB_TRANSFORM_NAMES)
JOB_TRANSFORM_AllJobsToAnnex @=end
    REQUIREMENTS TargetAnnexName =?= undefined
    SET TargetAnnexName "default-annex"
@end
